customer/urls.py
from django.contrib import admin
from django.urls import path

from customerapp import views

app_name = 'customerapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', views.CustomerListView.as_view(), name='customer-list'),
    path('customers/<int:pk>/', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('customers/create/', views.CustomerCreateView.as_view(), name='customer-create'),
    path('customers/<int:pk>/update/', views.CustomerUpdateView.as_view(), name='customer-update'),
    path('customers/<int:pk>/delete/', views.CustomerDeleteView.as_view(), name='customer-delete'),
]

customerapp/models.py
from django.db import models
from .constants import STATE_CHOICES

class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=100, null=True)
    zip_code = models.CharField(max_length=10,null=True)
    state = models.CharField(max_length=2, choices=STATE_CHOICES, default='CO')

    def __str__(self):
        return f"{self.first_name} {self.last_name} from {self.city}, {self.state}"

customerapp/views.py
from .views_customer import CustomerCreateView, CustomerDeleteView, CustomerDetailView, CustomerListView, CustomerUpdateView

customerapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Customers{% endblock %}</title>
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <header class="bg-primary py-3">
        <div class="container">
            <h1 class="text-white">Welcome to Customers App</h1>
        </div>
    </header>
    
    <nav>
        <!-- ... if I want to add navigation later ... -->
    </nav>
    
    <main class="container mt-4">
        {% block content %}
        <!-- a place for default content for child templates if exists -->
        {% endblock %}
    </main>

<footer>
    <div class="bg-light p-3">
        <p>&copy; 2023 Nik M. All rights reserved.</p>
    </div>
</footer>
<script>
    document.addEventListener("DOMContentLoaded", function() {
      const form = document.querySelector(".customer-form");
      const requiredInputs = form.querySelectorAll("[required]");
      const submitButton = form.querySelector("[type='submit']");
    
      function updateSubmitButtonState() {
        let allFieldsFilled = true;
        requiredInputs.forEach(input => {
          if (!input.value.trim()) {
            allFieldsFilled = false;
            return;
          }
        });
        submitButton.disabled = !allFieldsFilled;
      }
    
      requiredInputs.forEach(input => {
        input.addEventListener("input", updateSubmitButtonState);
      });
    
      updateSubmitButtonState();
    });
    </script>
    
</body>
</html>

customerapp/templates/customer/customer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete the customer record "{{ customer.first_name }} {{ customer.last_name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'customer-detail' customer.pk %}">Cancel</a>
  </form>
{% endblock %}

customerapp/templates/customer/customer_detail.html
{% extends 'base.html' %}

{% block title %}Customer Detail{% endblock %}

{% block content %}
<h1>Customer Detail</h1>
<p>First Name: {{ customer.first_name }}</p>
<p>Last Name: {{ customer.last_name }}</p>
<p>Address: {{ customer.address }}</p>
<p>City: {{ customer.city }}</p>
<p>Zip Code: {{ customer.zip_code }}</p>
<p>State: {{ customer.get_state_display }}</p>
<a href="{% url 'customer-update' customer.pk %}" class="btn btn-primary mb-3">Edit</a>
<form method="post" action="{% url 'customer-delete' customer.pk %}" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger mb-3">Delete</button>
</form>
{% endblock %}

customerapp/templates/customer/customer_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>{% if object %}Update{% else %}Create{% endif %} Customer</h1>
  <form method="post" class="form-row customer-form">
    {% csrf_token %}
    {{ form.as_p|safe }}
    <button type="submit" class="btn btn-primary mb-3">{% if object %}Update{% else %}Create{% endif %}</button>
  </form>
  <a href="{% url 'customer-list' %}">Back to Customers</a>
{% endblock %}

customerapp/templates/customer/customer_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Customer List</h1>
  <a href="{% url 'customer-create' %}" class="btn btn-success mb-3">Create New Customer</a>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers %}
        <tr class="{% cycle 'table-secondary' '' %}">
          <td>{{ customer.id }}</td>
          <td>
            <a href="{% url 'customer-detail' customer.pk %}">
              {{ customer.first_name }} {{ customer.last_name }}
            </a>
          </td>
          <td>
            <a href="{% url 'customer-update' customer.pk %}" class="btn btn-primary">Edit</a>
            <form method="post" action="{% url 'customer-delete' customer.pk %}" style="display: inline;">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}